const { test } = require('node:test')
const assert = require('node:assert/strict')
const { resolveHit, judgeHit, sliderPosition, watcherState, normalAudio } = require(process.env.SURVIVAL_TEST_BUILD + '/survival.js')
const { survivalConfig } = require(process.env.SURVIVAL_TEST_BUILD + '/survivalConfig.js')
const { eatingView } = require(process.env.SURVIVAL_TEST_BUILD + '/eatingSystem.js')
function sequence(hits) { let s = {progress:0, alert:0, status:'playing'}; for (const hit of hits) { if(s.status !== 'playing') break; s = resolveHit(s.progress,s.alert,hit) } return s }
test('ten Normal hits finish safely',()=>assert.deepEqual(sequence(Array(10).fill('normal')), {progress:10,alert:0,status:'success'}))
test('three Perfect hits lose',()=>assert.deepEqual(sequence(['perfect','perfect','perfect']),{progress:9,alert:102,status:'caught'}))
test('two Perfect hits then Miss lose',()=>assert.deepEqual(sequence(['perfect','perfect','miss']),{progress:6,alert:113,status:'caught'}))
test('Miss recovers only with Normal hits',()=>{let s=resolveHit(0,0,'miss');for(const a of [33,21,9,0]){s=resolveHit(s.progress,s.alert,'normal');assert.equal(s.alert,a)}})
test('final Perfect caps progress, charges full alert',()=>assert.deepEqual(resolveHit(9,20,'perfect'),{progress:10,alert:54,status:'success'}))
test('simultaneous completion and wakeup loses',()=>assert.deepEqual(resolveHit(8,75,'perfect'),{progress:10,alert:109,status:'caught'}))
test('Normal alert floor',()=>assert.equal(resolveHit(0,5,'normal').alert,0))
test('watcher boundaries',()=>{for(const [a,s] of [[0,'sleeping'],[33,'sleeping'],[34,'stirring'],[59,'stirring'],[60,'halfAwake'],[79,'halfAwake'],[80,'danger'],[99,'danger'],[100,'caught'],[113,'caught']])assert.equal(watcherState(a),s)})
test('inclusive safe and Perfect boundaries',()=>{for(const [p,h] of [[0,'miss'],[.299,'miss'],[.3,'normal'],[.469,'normal'],[.47,'perfect'],[.5,'perfect'],[.53,'perfect'],[.531,'normal'],[.7,'normal'],[.701,'miss'],[1,'miss']])assert.equal(judgeHit(p),h)})
test('slider bounces at the configured fixed speed',()=>{const duration=survivalConfig.slider.singlePassMs;for(const [passes,p] of [[0,0],[.5,.5],[1,1],[1.5,.5],[2,0],[2.5,.5]])assert.equal(sliderPosition(passes*duration),p)})
test('existing eating mapping including cross-phase Perfect',()=>{for(let p=0;p<=10;p++)assert.deepEqual(eatingView(p),{bites:Math.min(p,7),sips:Math.max(0,p-7)});assert.deepEqual(eatingView(resolveHit(6,0,'perfect').progress),{bites:7,sips:2})})
test('normal sounds follow original noodle/soup stages',()=>{assert.match(normalAudio(0),/slurp-short-01/);assert.match(normalAudio(6),/slurp-short-01/);assert.match(normalAudio(7),/drink-small-01/);assert.match(normalAudio(8),/drink-small-02/);assert.match(normalAudio(9),/drink-final/)})
